name: Cypress Tests

on:
  push:
    branches:
      - chairlyo-aashika

  pull_request:
    branches:
      - chairlyo-aashika

  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
          CYPRESS_EMAIL: ${{ secrets.CYPRESS_EMAIL }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          BRANCH_ADMIN_EMAIL: ${{ secrets.BRANCH_ADMIN_EMAIL }}
          BRANCH_ADMIN_PASSWORD: ${{ secrets.BRANCH_ADMIN_PASSWORD }}
        with:
          browser: chrome
